### ISSUE TITLE
Food Scraps And Walkie playing audio globally

### ISSUE THREAD

**Issue by ZehsTeam** [hoffor/MyLethalCompanyMods#3]
Hey, I noticed that the food scrap items in your [Food Scraps And Walkie](https://thunderstore.io/c/lethal-company/p/hoffr/Food_Scraps_And_Walkie/) Lethal Company mod have global audio. Meaning if someone picks up or drops one of the food scrap items everyone can hear the sounds for anywhere in the map.

To fix this, in the AudioSource for each food scrap item, you need to set the `Spatial Blend` to 1, set the AudioRolloffMode to either Linear or Custom, and set the Min/Max distance. If you have a decompiled version of Lethal Company as a Unity project you could reference one of the vanilla scraps AudioSource. You could also reference the values of the walkie AudioSource since that one seems to work as intended.

**Comment by hoffor** [comment]
this item is based off a vanilla noisemaker prop, and all parameters are already how you recommend (also for distance, min=4, max=21)

i last tested this mod in v62 and my friends and i did not experience the issue you mention, but there was one time in a morecompany group where we did notice the walkie audio clip playing twice (once slightly delayed) for only the host

in other 2-player sessions it was not duplicated for the host. unsure if that could at all be related or if that's just a morecompany bug (morecompany has lots of desync issues i know that)

i know there are also rare times in heavily modded lobbies (unrelated to this mod) where picking up/placing items plays those sounds globally, haven't figured out why that is

but yeah i haven't tested your issue in v68, but things shouldn't be any different from v62 i think

**Comment by ZehsTeam** [comment]
@hoffor I'm saying that your food scrap items have global audio since the [`Spatial Blend`](https://docs.unity3d.com/ScriptReference/AudioSource-spatialBlend.html) and [`Volume Rolloff`](https://docs.unity3d.com/ScriptReference/AudioRolloffMode.html) is set incorrectly on the AudioSources.

While I was on the ship, I had a crewmate pick up and drop the **Bread**, **Burger**, **Cake**, **Coffee**, and **Cookie** scrap items while they were inside the facility and I could hear the sounds of those items being picked up and dropped.



#### <img src="https://i.imgur.com/RiB59Xp.png" width="15px"> This should not be happening!

> **[!NOTE] The Cursed Walkie scrap item works perfectly fine.**

---

#### To fix this issue:
For each of your food scrap items, on the AudioSource component, you need to set [`Spatial Blend`](https://docs.unity3d.com/ScriptReference/AudioSource-spatialBlend.html) to `1` and [`Volume Rolloff`](https://docs.unity3d.com/ScriptReference/AudioRolloffMode.html) to **Linear Rolloff**. Then you need to set the `Min Distance` and `Max Distance`.

---

I decompiled your mods' AssetBundle to a Unity project and checked the properties of each scrap item.

<div>
    <img src="https://i.imgur.com/cHozOhE.png" width="33%">
    <img src="https://i.imgur.com/YRsZStb.png" width="33%">
    <img src="https://i.imgur.com/659NW7g.png" width="33%">
</div>
<div>
    <img src="https://i.imgur.com/bveqaXp.png" width="33%">
    <img src="https://i.imgur.com/fT5LK6r.png" width="33%">
    <img src="https://i.imgur.com/3Oeut65.png" width="33%">
</div>
<h3>Vanilla item for reference</h3>
<img src="https://i.imgur.com/OkWMGrA.png" width="100%">

**Comment by hoffor** [comment]
ah, simple late AM misread. food items, not the walkie. got it, that's all you had to say lol. thanks for the report, i'll be fixing this

**Comment by hoffor** [comment]
fixed the issue and another too, again i appreciate it

https://thunderstore.io/c/lethal-company/p/hoffr/Food_Scraps_And_Walkie/changelog/
